Repository redhat-performance/cloud-governance, pull requests merged in 2023-06, with the labels that each got.

#604 Added lambda for approving the ticket
  aws_lambda_functions/CloudResourceOrchestration/lambda_function.py
  aws_lambda_functions/CloudResourceOrchestration/requirements.txt
  aws_lambda_functions/CloudResourceOrchestration/upload_to_lambda.sh
Labels: enhancement

#608 Fixed the mail alerts subject, added the template to manifest.in
  MANIFEST.in
  cloud_governance/common/mails/mail_message.py
  cloud_governance/common/mails/postfix.py
Labels: bug, Approved

#610 Incorporated the email corrections, Increase AWS API call limits
  cloud_governance/common/clouds/aws/cost_explorer/cost_explorer_operations.py
  cloud_governance/common/mails/mail_message.py
  cloud_governance/common/mails/templates/cro_request_for_manager_approval.j2
  jenkins/cloud_resource_orchestration/run_cloud_resource_orchestration.py
Labels: documentation

#611 Enabled the mail alert data to save in es
  cloud_governance/cloud_resource_orchestration/aws/ec2/monitor_tickets.py
  cloud_governance/cloud_resource_orchestration/aws/ec2/run_cro.py
  cloud_governance/common/mails/postfix.py
Labels: bug, Approved

#613 Added the user missing ticket cost to es
  cloud_governance/cloud_resource_orchestration/aws/ec2/cost_over_usage.py
  cloud_governance/common/elasticsearch/elasticsearch_operations.py
Labels: bug, Approved

#615 not perform action if it is already inprogress state
  cloud_governance/cloud_resource_orchestration/aws/ec2/tag_cro_instances.py
  cloud_governance/common/jira/jira_operations.py
Labels: bug, Approved

#618 Fixed the date range issue
  cloud_governance/cloud_resource_orchestration/aws/ec2/cost_over_usage.py
Labels: bug, Approved

#616 Added the manager to manager/cloud_admin ticket approval
  cloud_governance/cloud_resource_orchestration/aws/ec2/monitor_tickets.py
  cloud_governance/common/ldap/ldap_search.py
  cloud_governance/common/mails/mail_message.py
  cloud_governance/common/mails/templates/cro_request_for_manager_approval.j2
  cloud_governance/main/environment_variables.py
  tests/unittest/cloud_governance/common/ldap/test_ldap_search.py
Labels: enhancement

#619 CRO: Attached the untagged instances to the email body
  cloud_governance/cloud_resource_orchestration/aws/ec2/monitor_tickets.py
  cloud_governance/common/clouds/aws/ec2/ec2_operations.py
  cloud_governance/common/mails/mail_message.py
Labels: enhancement, Approved

#620 Update Python package requirements
  requirements.txt
  setup.py
  tests_requirements.txt
Labels: bug, Approved

#614 Added the CloudSensei
  .gitignore
  cloudsensei/README.md
  cloudsensei/agg_lambda/lambda_function.py
  cloudsensei/agg_lambda/run.sh
  cloudsensei/email_template.j2
  cloudsensei/env.conf
  cloudsensei/es_operations.py
  cloudsensei/lambda_function.py
  cloudsensei/requirements.txt
  cloudsensei/run.sh
  cloudsensei/send_email.py
  cloudsensei/slack_operations.py
  cloudsensei/terraform/CloudSenseiLambdaPolicy.j2
  cloudsensei/terraform/CloudSenseiLambdaRole.json
  cloudsensei/terraform/Template.py
  cloudsensei/terraform/event_bridge.tf
  cloudsensei/terraform/lambda.tf
  cloudsensei/terraform/main.tf
  cloudsensei/terraform/variables.tf
Labels: enhancement, Approved

#617 Suggesting improvements for html tables in email
  cloud_governance/common/mails/mail_message.py
Labels: enhancement, Approved

#622 [doc-updates]: Minor nit to README.md
  cloudsensei/README.md
Labels: documentation
