Repository redhat-performance/cloud-governance, pull requests merged in 2023-07, with the labels that each got.

#626 Check if ticket is extended before closing the ticket
  cloud_governance/cloud_resource_orchestration/aws/ec2/monitor_tickets.py
Labels: bug, Approved

#628 Error when fetching azure daily cost usage
  cloud_governance/common/clouds/azure/cost_management/cost_management_operations.py
  tests/integration/cloud_governance/common/clouds/azure/cost_management/test_cost_management_operations.py
Labels: bug, Approved

#629 Added the http response code error of azure reports
  cloud_governance/common/clouds/azure/cost_management/cost_management_operations.py
  tests/integration/cloud_governance/common/clouds/azure/cost_management/test_cost_management_operations.py
Labels: bug, Approved

#631 Removed the parallel execution
  cloud_governance/common/clouds/aws/utils/utils.py
Labels: bug, Approved

#630 Fix GitHub Actions PR vulnerability
  .github/workflows/PR.yml
Labels: Approved, dependencies, Security Alert, ok-to-test

#633 Added the type synchronize to the pr types
  .github/workflows/PR.yml
Labels: Approved, ok-to-test

#632 Added the extended days, cost while tagging
  cloud_governance/cloud_resource_orchestration/aws/ec2/monitor_tickets.py
  cloud_governance/cloud_resource_orchestration/aws/ec2/tag_cro_instances.py
  cloud_governance/common/jira/jira_operations.py
Labels: documentation, Approved, dependencies, ok-to-test

#623 added the user daily cost usage
  cloud_governance/cloud_resource_orchestration/aws/ec2/collect_cro_reports.py
Labels: documentation, ok-to-test

#602 Added the docs for creating Jenkins slave & running containers - [ WIP ]
  iam/clouds/aws/CloudGovernanceDeletePolicy.json
  images/jenkins/add_creds.png
  images/jenkins/jenkins_config_file.png
  images/jenkins/manage_jenkins.png
  images/jenkins/manage_nodes.png
  images/jenkins/new_node.png
  images/jenkins/slave_node.png
  jenkins/README.md
  jenkins/Step_by_Step.md
  jenkins/docker-compose.yml
  jenkins/podman_pod.yml
Labels: documentation, ok-to-test

#634 Fixed the agg policy alert message
  cloud_governance/policy/common_policies/send_aggregated_alerts.py
  jenkins/clouds/aws/daily/policies/run_policies.py
Labels: bug, ok-to-test

#635 Updates the CloudSensei Subject info
  cloudsensei/agg_lambda/lambda_function.py
  cloudsensei/lambda_function.py
Labels: Approved, ok-to-test

#638 Removed the pr opened type in pr.yml
  .github/workflows/PR.yml
Labels: bug, Security Alert, ok-to-test

#636 Added the backend configuration for the terraform
  cloudsensei/agg_lambda/lambda_function.py
  cloudsensei/env.conf
  cloudsensei/env.sh
  cloudsensei/run.sh
  cloudsensei/terraform/Template.py
  cloudsensei/terraform/backend.j2
Labels: documentation, ok-to-test

#639 Added concurrency feature to main.yml
  .github/workflows/Build.yml
  jenkins/clouds/aws/daily/org_cost_explorer/Jenkinsfile
  jenkins/clouds/aws/daily/org_cost_explorer/run_org_upload_es.py
Labels: Approved

#641 Fixed some changes to the tag_iam_user
  cloud_governance/policy/policy_operations/aws/tag_user/tag_iam_user.py
Labels: bug, ok-to-test

#643 Push the data elastic search after getting the results
  cloud_governance/common/elasticsearch/elasticsearch_operations.py
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/policy_operations/aws/zombie_non_cluster/run_zombie_non_cluster_policies.py
  cloud_governance/policy/policy_operations/aws/zombie_non_cluster/zombie_non_cluster_polices.py
Labels: bug, documentation, ok-to-test

#645 Fixed the elasticsearch operations error
  cloud_governance/common/elasticsearch/elasticsearch_operations.py
Labels: bug, ok-to-test

#644 Add the cro flow diagram
  images/CloudResourceOrchestration.jpg
Labels: documentation, ok-to-test

#646 need the approve to run the stop
  .github/workflows/PR.yml
Labels: bug, ok-to-test

#648 Added the env variable for delete resource
  cloud_governance/common/elasticsearch/elasticsearch_operations.py
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/policy_operations/aws/zombie_cluster/zombie_cluster_common_methods.py
  cloud_governance/policy/policy_operations/aws/zombie_non_cluster/run_zombie_non_cluster_policies.py
Labels: bug, ok-to-test
