Repository redhat-performance/cloud-governance, pull requests merged in 2025-05, with the labels that each got.

#913 Fix the cost-over-usage index
  jenkins/clouds/aws/weekly/cost_over_usage/run_upload_es.py
Labels: documentation

#914 Update mail to yinsong
  aws_lambda_functions/CloudResourceOrchestration/lambda_function.py
  cloud_governance/common/mails/postfix.py
  cloud_governance/policy/aws/cost_over_usage.py
  cloud_governance/policy/policy_operations/aws/zombie_non_cluster/run_zombie_non_cluster_policies.py
  iam/clouds/aws/payer_roles/CloudGovernanceCostExplorerReadRole.json
  jenkins/cloud_resource_orchestration/Jenkinsfile
  jenkins/cloud_resource_orchestration/run_cloud_resource_orchestration.py
  jenkins/clouds/aws/daily/cost_explorer/Jenkinsfile
  jenkins/clouds/aws/daily/org_cost_explorer/Jenkinsfile
  jenkins/clouds/aws/daily/policies/Jenkinsfile
  jenkins/clouds/aws/hourly/tagging/Jenkinsfile
  jenkins/clouds/aws/monthly/Jenkinsfile
  jenkins/clouds/aws/weekly/cost_over_usage/Jenkinsfile
  jenkins/clouds/azure/daily/cost_reports/Jenkinsfile
  jenkins/clouds/azure/daily/policies/Jenkinsfile
  jenkins/clouds/gcp/daily/cost_reports/Jenkinsfile
  jenkins/clouds/ibm/daily/cost_billings/Jenkinsfile
  jenkins/clouds/ibm/hourly/tagging/Jenkinsfile
  jenkins/clouds/ibm/monthly/cost_invoice/Jenkinsfile
  jenkins/clouds/ibm/weekly/cost_over_usage/Jenkinsfile
  jenkins/clouds/ibm/weekly/cost_over_usage/run_policies.py
  jenkins/tenant/aws/default/PolicyJenkinsfileDaily
  jenkins/tenant/aws/default/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_01/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_02/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_03/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_03/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ovn/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_01/TaggingJenkinsfileHourly
  jenkins/tenant/aws/qe/qe_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_02/TaggingJenkinsfileHourly
Labels: documentation, ok-to-test

#918 fix aggregate email alert
  cloud_governance/common/mails/postfix.py
  cloud_governance/main/environment_variables.py
Labels: bug, ok-to-test
