Repository redhat-performance/cloud-governance, pull requests merged in 2025-04, with the labels that each got.

#902 Fixed the tag not found error
  cloud_governance/policy/ibm/ibm_cost_report.py
  jenkins/clouds/ibm/hourly/tagging/tagging.py
Labels: bug, ok-to-test

#903 Add try/catch aroung flaky methods
  cloud_governance/policy/policy_operations/aws/tag_cluster/tag_cluster_resouces.py
  cloud_governance/policy/policy_runners/aws/upload_s3.py
Labels: bug, ok-to-test

#904 update boto3 package
  cloud_governance/common/clouds/aws/ec2/ec2_operations.py
  requirements.txt
  setup.py
  tests_requirements.txt
Labels: dependencies, ok-to-test

#905 Adding creds auth to elasticsearch
  cloud_governance/common/elasticsearch/elasticsearch_operations.py
  cloud_governance/main/environment_variables.py
Labels: enhancement, ok-to-test

#906 Update latest policy list
  cloud_governance/main/environment_variables.py
  cloud_governance/main/example.yaml
  cloud_governance/main/main.py
Labels: bug, ok-to-test

#907 Fix the errors
  cloud_governance/main/environment_variables.py
  jenkins/clouds/aws/daily/policies/Jenkinsfile
Labels: bug, ok-to-test

#909 Disable gitleaks
  jenkins/clouds/aws/daily/policies/run_policies.py
Labels: dependencies, ok-to-test

#910 Modify zombie_cluster_reosurce cluster_prefix
  cloud_governance/common/clouds/aws/ec2/ec2_operations.py
  cloud_governance/common/clouds/aws/utils/utils.py
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/aws/zombie_cluster_resource.py
  cloud_governance/policy/policy_operations/aws/zombie_cluster/run_zombie_cluster_resources.py
  jenkins/clouds/aws/daily/policies/run_policies.py
  jenkins/tenant/aws/common/run_policies.py
  tests/unittest/cloud_governance/aws/zombie_cluster/test_zombie_cluster_resources.py
Labels: enhancement, ok-to-test

#911 add zombie cluster resource policy
  cloud_governance/main/environment_variables.py
Labels: enhancement

#912 Update the quay image to cloud-governance
  Docker/centos-stream8-jenkins-slave/Dockerfile
  Docker/fedora-38-jenkins-slave/Dockerfile
  jenkins/cloud_resource_orchestration/Jenkinsfile
  jenkins/clouds/aws/daily/cost_explorer/Jenkinsfile
  jenkins/clouds/aws/daily/org_cost_explorer/Jenkinsfile
  jenkins/clouds/aws/daily/policies/Jenkinsfile
  jenkins/clouds/aws/hourly/tagging/Jenkinsfile
  jenkins/clouds/aws/monthly/Jenkinsfile
  jenkins/clouds/aws/weekly/cost_over_usage/Jenkinsfile
  jenkins/clouds/azure/daily/cost_reports/Jenkinsfile
  jenkins/clouds/azure/daily/policies/Jenkinsfile
  jenkins/clouds/gcp/daily/cost_reports/Jenkinsfile
  jenkins/clouds/ibm/daily/cost_billings/Jenkinsfile
  jenkins/clouds/ibm/hourly/tagging/Jenkinsfile
  jenkins/clouds/ibm/monthly/cost_invoice/Jenkinsfile
  jenkins/clouds/ibm/weekly/cost_over_usage/Jenkinsfile
  jenkins/tenant/aws/default/PolicyJenkinsfileDaily
  jenkins/tenant/aws/default/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_01/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_02/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_03/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_03/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ovn/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_01/TaggingJenkinsfileHourly
  jenkins/tenant/aws/qe/qe_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/qe/qe_02/TaggingJenkinsfileHourly
  pod_yaml/postfix_pod.yml
Labels: documentation, ok-to-test
