Repository redhat-performance/cloud-governance, pull requests merged in 2025-07, with the labels that each got.

#922 Fix skip policy alert
  cloud_governance/main/environment_variables.py
  jenkins/tenant/aws/ecoeng_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_03/PolicyJenkinsfileDaily
Labels: bug

#924 fix variable quotes
  jenkins/tenant/aws/common/run_policies.py
Labels: bug, ok-to-test

#927 Update cluster_prefix from string to list
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/aws/zombie_cluster_resource.py
  cloud_governance/policy/policy_operations/aws/tag_cluster/run_tag_cluster_resouces.py
  cloud_governance/policy/policy_operations/aws/tag_cluster/tag_cluster_resouces.py
  tests/integration/cloud_governance/aws/zombie_cluster/test_ec2_zombie_delete.py
  tests/integration/cloud_governance/aws/zombie_cluster/test_iam_zombie_delete.py
  tests/integration/cloud_governance/aws/zombie_cluster/test_s3_zombie_delete.py
  tests/unittest/cloud_governance/aws/tag_cluster/test_tag_cluster_resources.py
  tests/unittest/cloud_governance/aws/zombie_cluster/test_zombie_cluster_resources.py
  tests/unittest/cloud_governance/aws/zombie_cluster/test_zombie_ec2_cluster_delete_resource.py
  tests/unittest/cloud_governance/aws/zombie_cluster/test_zombie_iam_cluster_delete_resource.py
  tests/unittest/cloud_governance/aws/zombie_cluster/test_zombie_s3_cluster_delete_resource.py
Labels: bug, ok-to-test

#933 Fix and enhance the RESOURCE_TO_TAG option
  POLICIES.md
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/ibm/tag_resources.py
Labels: bug, enhancement, ok-to-test

#934 Missing IAM for unused_access_key policy
  cloud_governance/common/clouds/aws/iam/iam_operations.py
  cloud_governance/main/environment_variables.py
  cloud_governance/policy/aws/unused_access_key.py
  iam/clouds/aws/CloudGovernanceInfra/CloudGovernanceDeletePolicy.json
  iam/clouds/aws/CloudGovernanceInfra/CloudGovernanceReadPolicy.json
Labels: bug, ok-to-test, lgtm

#936 Removed zombie resources , moved appeng-ai to gr02
  jenkins/tenant/aws/ecoeng_01/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_01/TaggingJenkinsfileHourly
  jenkins/tenant/aws/ecoeng_02/PolicyJenkinsfileDaily
  jenkins/tenant/aws/ecoeng_02/TaggingJenkinsfileHourly
Labels: enhancement, ok-to-test, lgtm

#930 add tenant health check jobs
  jenkins/tenant/service_checks/ecoeng/Haim-VM-reboot/Jenkinsfile
  jenkins/tenant/service_checks/ecoeng/Haim-VMServiceCheck/Jenkinsfile
Labels: documentation, lgtm
